### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by niko1point0** [cschied/q2vkpt#14]
Thank you so much for all the hard work, I’m a huge Quake 2 fan. Can you please make RTX support for Quake 1 and 3? It would be great for owners of RTX cards to have more games to play for free, after spending a lot of money on the GPU

**Comment by niko1point0** [comment]
Is it possible to implement DirectX 12 for a side-by-side comparison?

**Comment by cschied** [comment]
If time permits I might start to work on Q1VKPT as the renderes should be fairly similar.

As of Q3 I'm corrupted as a heavy picmip player and I don't think a multi-player game has a strong benefit from the improved graphics.

Radeon Rays would mean a full rewrite of VKPT and won't happen. Please push for AMD to support a vendor neutral vulkan extension.

**Comment by niko1point0** [comment]
What about RTX? Is RTX exclusive to Nvidia?

**Comment by niko1point0** [comment]
Also, do you have Patreon? With Patreon, people can donate money to you, and request for RTX support in other games
