### ISSUE TITLE
Build fails with following errors

### ISSUE THREAD

**Issue by Mcilie** [cschied/q2vkpt#16]
Hello, after installing all the deps and running `sudo make -j 10 ` i get
`[CC] .q2pro/src/client/refresh.o
[CC] .q2pro/src/refresh/images.o
[CC] .baseq2/src/baseq2/g_svcmds.o
[CC] .baseq2/src/baseq2/g_spawn.o
[CC] .baseq2/src/baseq2/g_target.o
[CC] .baseq2/src/baseq2/g_trigger.o
[CC] .baseq2/src/baseq2/g_turret.o
[CC] .baseq2/src/baseq2/g_utils.o
[CC] .baseq2/src/baseq2/g_weapon.o
[CC] .baseq2/src/baseq2/m_actor.o
src/refresh/images.c: In function ‘load_img’:
src/refresh/images.c:1795:7: error: ‘image_t {aka struct image_s}’ has no member named ‘pix_data’
  image->pix_data = pic;
       ^~
src/refresh/images.c: In function ‘IMG_FreeUnused’:
src/refresh/images.c:2042:35: error: ‘image_t {aka struct image_s}’ has no member named ‘pixels’
             Com_PageInMemory(image->pixels[0], image->upload_width * image->upload_height * 4);
                                   ^~
Makefile:741: recipe for target '.q2pro/src/refresh/images.o' failed
make: *** [.q2pro/src/refresh/images.o] Error 1
make: *** Waiting for unfinished jobs....
src/client/refresh.c: In function ‘CL_InitRefresh’:
src/client/refresh.c:299:35: error: ‘VID_REF’ undeclared (first use in this function); did you mean ‘VID_Init’?
     vid_ref = Cvar_Get("vid_ref", VID_REF, CVAR_ROM);
                                   ^~~~~~~
                                   VID_Init
src/client/refresh.c:299:35: note: each undeclared identifier is reported only once for each function it appears in
Makefile:741: recipe for target '.q2pro/src/client/re
fresh.o' failed
make: *** [.q2pro/src/client/refresh.o] Error 1`
thanks

**Comment by Doomsdayrs** [comment]
Same issue here, seems to be a variable error

**Comment by cschied** [comment]
it looks like the .config file is not correct.

Did you copy over the config_vkpt file to .config?

**Comment by Doomsdayrs** [comment]
There is no .config folder nor file

**Comment by cschied** [comment]
`cp config_vkpt .config` should fix the build

**Comment by cschied** [comment]
Please refer to https://github.com/cschied/q2vkpt/issues/12#issuecomment-455896409
