### ISSUE TITLE
More graphics control.

### ISSUE THREAD

**Issue by ghost345** [cschied/q2vkpt#19]
Hi!
This technology is amazing! And your realization is the best, that i've seen yet!

Is it possible to control graphics with changing parametres via console commands or changing settings in config files? I'd like to change roughness of the surfaces, control enable\disable denoising or maybe view render channels and increase energy of ray. 

Are there more control than F1\F2?

**Comment by cschied** [comment]
Hi,

there is vkpt_reconstruction 0/1/2 to show denoising input, reconstruction and temporal filtering weights.

Other than that you would need to modify the shader. (src/refresh/vkpt/shader/path_tracer.h)

**Comment by ghost345** [comment]
Thanks!
