### ISSUE TITLE
1st line in readme should be "RTX only" (

### ISSUE THREAD

**Issue by necros2k7** [cschied/q2vkpt#20]
or list with compatible GPUs

**Comment by hanatos** [comment]
also see issue #11 about that.

**Comment by SouldomainTM** [comment]
Seems that's because it's not RTX only. It's RT cores only, so require hardware support. Eventually Intel and AMD also are going to have RT cores.

1 AMD, and 1 Intel dev is working on the VK_NV_ray_tracing extension. It ain't just Nvidia.

**Comment by Continous** [comment]
This is no longer relevant, since Pascal GPUs received VulkanRT extension support, which means AMD cards can as well. It'd be more relevant to list a necessity for RT extensions.
