### ISSUE TITLE
Resolution auto lowered when set above 1080p?

### ISSUE THREAD

**Issue by Slippi1** [cschied/q2vkpt#22]
I love this project so much and admire that I can be a part of the future of real time graphics!

That said, I've been having an issue where anytime I set the resolution higher than 1080p, it gets lowered. 
Example: I set the resolution to 2560x1440 and it gets lowered to 2048x1152. Weirdly, setting the resolution to 4k also changes the resolution to 2048x1152. I am playing this on a 1440p monitor, so maybe that has something to do with it?

Thank you so much for making this project!

**Comment by mastan-rus** [comment]
@Slippi1 
I have 1440p monitor and q2vkpt works at 2560x1440. But every time I start game it starts windowed and I have to press Alt-Enter twice to go fullscreen again.

**Comment by svonolfen** [comment]
Hi,
In my case, high-DPI settings in Windows prevented to set higher resolutions than 720p. No matter which full-screen resolution I would chose, the game would always revert back to this resolution.

What fixed it for me:
1) go to properties of q2vkpt.exe
2) in "Compatibility" tab, click "Change high DPI settings"
3) chose "Application" for the option "Override high DPI scaling behavior"

Hope this helps. 

Regards,
Stefan

**Comment by Slippi1** [comment]
> Hi,
> In my case, high-DPI settings in Windows prevented to set higher resolutions than 720p. No matter which full-screen resolution I would chose, the game would always revert back to this resolution.
> 
> What fixed it for me:
> 
> 1. go to properties of q2vkpt.exe
> 2. in "Compatibility" tab, click "Change high DPI settings"
> 3. chose "Application" for the option "Override high DPI scaling behavior"
> 
> Hope this helps.
> 
> Regards,
> Stefan

Hello!

I forgot to get back to you, but your solution worked! Now I have full control over render window size and can take pretty 8k screenshots! 

Thank you so much!
