### ISSUE TITLE
Rendering bug with weapon and enemies

### ISSUE THREAD

**Issue by Andy1977** [cschied/q2vkpt#36]
Hello all,

I have rendering bugs with the weapon and the enemies. (animated objects?)
The objects are rendered as seen in the glitch videos Nr. 1 (link from brechpunkt.de to youtube).
Link to the video on youtube: https://youtu.be/AIsQ5h0bkDw

I have a gtx 2060 running on windows 10 with the newest drivers.
I downloaded the windows binary from github.

I have installed in the past several Vulkan SDK's.
Could it be, that a old runtime library was not entirely removed from my system?

Thanks in advance for your help

Andy

**Comment by cschied** [comment]
I've seen one youtube video that seems to match your description, unfortunately I cannot find it anymore. The Vulkan SDKs shouldn't have any effect as the shaders are already prebuilt.

Can you post your exact nvidia driver version? Could you provide some screenshots?

**Comment by Andy1977** [comment]
Thanks for your reply.

It was my mistake! 
I downloaded "quake 2 test" and not the final quake 2 demo version 3.12.
I didn´t know, that id-software had released a "test demo" before the final product
came out.

I download the "quake 2 test" from the internet archive. It is the first entry when
you search with the keyword "quake 2 demo" on google.
Adding a note in the readme file would be a good thing.

You can see the difference in the filesize of the pak-file: The "test demo" has a size
around 23 MB and the quake 2 demo 3.12 has a file size of 46 MB.

Regards
Andy
