### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by XakepSDK** [cschied/q2vkpt#4]
When i'm building, i'm getting this error:
`make clean; make strip`
https://gist.github.com/XakepSDK/79c1b88ff38473c7c8192fce6c0a4f2b
My `.config` file:
https://gist.github.com/XakepSDK/d677a54a1a62b6420f65fbf9a56b27f6

**Comment by cschied** [comment]
Hi,

can you try with this file as .config: https://github.com/cschied/q2vkpt/blob/master/config_vkpt

**Comment by XakepSDK** [comment]
Yeah, it works! I'm getting some warnings. Does this config enable ray-tracing?

**Comment by cschied** [comment]
What kind of warnings are you getting? This config enables the VKPT renderer which gives you full hardware accelerated path tracing

**Comment by XakepSDK** [comment]
https://gist.github.com/XakepSDK/4bd093f16168a5838f471ad59d881921

**Comment by cschied** [comment]
Yes, these warnings are expected and safe to ignore.

**Comment by XakepSDK** [comment]
Thanks for help!
