### ISSUE TITLE
Weapons don't display

### ISSUE THREAD

**Issue by Siphonay** [cschied/q2vkpt#7]
As seen in the following screenshot, the first person model of the weapons aren't rendered on my game.

I'm using the precompiled Windows binaries as well.

If that's of any releavance, my GPU is a RTX 2070, and I'm using the .pak files from the Steam version of the game. I can provide any other informations if needed.

Please do tell me if it's anything I'm doing wrong on my end!

![image](https://user-images.githubusercontent.com/6833300/51404890-103b4280-1b55-11e9-9f18-18b0f2cf7c08.png)

**Comment by cschied** [comment]
Hi,

this is an error in the default configuration and addressed with the new uploaded release.

Use the "~" key to open the console and type "hand 0" to display the weapon model.

**Comment by Siphonay** [comment]
This worked! Thank you 👍
