### ISSUE TITLE
F1 KEY

### ISSUE THREAD

**Issue by OmegaMinus1** [cschied/q2vkpt#9]
For me Pressing F1 causes all the surfaces to mirror like 10 bounce

Running the binaries from GitHub.
Running the free pak files.

![image1](https://user-images.githubusercontent.com/7004100/51418331-74a3d500-1b48-11e9-8887-fa7080e60a42.png)

![image2](https://user-images.githubusercontent.com/7004100/51418332-74a3d500-1b48-11e9-9df8-6db4dcfa167b.png)

**Comment by muddymind** [comment]
Just press F2 and it will return to the normal. Remap the Help computer key to F3 to open the objective screen.
